language:
    - cpp
compiler:
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get install libboost-all-dev
install:
    - mkdir build && cd build
    - cmake ..
    - make -j 2 -C ext
    - make -j 2
script:
    - make test
